apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ellipsoid-ing
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # This is here for backwards compatibility
  # I sent the IP address to prof. Černý and it's easier to support it for now than to send other messages
  - http:
      paths:
      - path: /
        backend:
          serviceName: ellipsoid-svc
          servicePort: 80
  - host: ellipsoid.mladedav.ml
    http:
      paths:
      - path: /
        backend:
          serviceName: ellipsoid-svc
          servicePort: 80
