apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ellipsoid-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # - host:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ellipsoid-svc
          servicePort: 80
